//! Manual bindings for Zephyr kernel internals needed by the full-Rust semaphore.
//!
//! In production, these would be auto-generated by `bindgen` from:
//!   - `${ZEPHYR_BASE}/kernel/include/ksched.h`
//!   - `${ZEPHYR_BASE}/kernel/include/wait_q.h`
//!   - `${ZEPHYR_BASE}/kernel/include/kernel_internal.h`
//!   - `${ZEPHYR_BASE}/include/zephyr/spinlock.h`
//!   - `${ZEPHYR_BASE}/include/zephyr/kernel.h` (struct k_sem layout)
//!
//! These are kernel-internal symbols — they are NOT part of Zephyr's stable API.
//! The C shim (gale_sem.c) uses them via `#include <ksched.h>` etc.
//! For a full-Rust replacement, we need the same access.
//!
//! ## Bindgen strategy (production)
//!
//! 1. Create `wrapper.h` that includes the kernel-internal headers.
//! 2. Run bindgen with the Zephyr build system's include paths:
//!    ```
//!    bindgen wrapper.h \
//!      -I ${ZEPHYR_BASE}/kernel/include \
//!      -I ${ZEPHYR_BASE}/include \
//!      -I ${ARCH_DIR}/${ARCH}/include \
//!      --allowlist-function "z_unpend_first_thread|z_pend_curr|..." \
//!      --allowlist-type "k_sem|k_spinlock|k_spinlock_key_t|k_thread" \
//!      -o kernel_sys.rs
//!    ```
//! 3. Integrate into CMake/Bazel so it regenerates on Zephyr version bumps.
//!
//! ## Why manual bindings for the POC
//!
//! Zephyr kernel headers are heavily macro-laden and config-dependent.
//! Running bindgen requires a full Zephyr build context (config, arch, toolchain).
//! For the POC, manual bindings let us validate the architecture without that
//! complexity.

#![allow(non_camel_case_types)]
#![allow(dead_code)]

use core::ffi::c_void;

// ---------------------------------------------------------------------------
// Opaque Zephyr types
// ---------------------------------------------------------------------------

/// Zephyr's `_wait_q_t` — opaque wait queue.
///
/// Actual layout depends on CONFIG (dlist or rbtree).
/// We only pass pointers, so an opaque type suffices.
///
/// C definition (from kernel_structs.h):
///   typedef struct { ... } _wait_q_t;
#[repr(C)]
pub struct _wait_q_t {
    _opaque: [u8; 0],
}

/// Zephyr's `struct k_thread` — opaque thread descriptor.
///
/// We only pass pointers, never inspect fields.
#[repr(C)]
pub struct k_thread {
    _opaque: [u8; 0],
}

/// Zephyr's `struct k_spinlock` — interrupt-disabling spinlock.
///
/// C definition (from spinlock.h):
///   struct k_spinlock {
///       #ifdef CONFIG_SMP
///       atomic_t locked;  // or ticket fields
///       #endif
///       #ifdef CONFIG_SPIN_VALIDATE
///       /* validation fields */
///       #endif
///   };
///
/// On uniprocessor (qemu_cortex_m3), this is typically empty or just
/// validation state. We need ABI-compatible layout per config.
///
/// For the POC we treat it as opaque and pass pointers to the existing
/// C-allocated spinlock. In production, bindgen generates the real layout.
#[repr(C)]
pub struct k_spinlock {
    _opaque: [u8; 0],
}

/// Zephyr's `k_spinlock_key_t` — interrupt state saved by k_spin_lock.
///
/// C definition (from spinlock.h):
///   struct z_spinlock_key { int key; };
///   typedef struct z_spinlock_key k_spinlock_key_t;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct k_spinlock_key_t {
    pub key: i32,
}

/// Zephyr's `k_timeout_t` — timeout specification.
///
/// C definition (from sys_clock.h):
///   typedef struct { k_ticks_t ticks; } k_timeout_t;
///   typedef int64_t k_ticks_t;  (typically)
///
/// K_NO_WAIT = { .ticks = 0 }
/// K_FOREVER = { .ticks = -1 } (or INT64_MAX for absolute)
#[repr(C)]
#[derive(Clone, Copy)]
pub struct k_timeout_t {
    pub ticks: i64,
}

impl k_timeout_t {
    /// K_NO_WAIT — return immediately if not available.
    pub const NO_WAIT: Self = k_timeout_t { ticks: 0 };

    /// K_FOREVER — wait indefinitely.
    pub const FOREVER: Self = k_timeout_t { ticks: -1 };

    /// Check if this is K_NO_WAIT.
    pub fn is_no_wait(self) -> bool {
        self.ticks == 0
    }
}

/// Zephyr's `struct k_sem` — the kernel semaphore object.
///
/// C definition (from kernel.h:3607):
///   struct k_sem {
///       _wait_q_t wait_q;
///       unsigned int count;
///       unsigned int limit;
///       Z_DECL_POLL_EVENT        // conditional
///       SYS_PORT_TRACING_TRACKING_FIELD(k_sem)  // conditional
///       #ifdef CONFIG_OBJ_CORE_SEM
///       struct k_obj_core obj_core;
///       #endif
///   };
///
/// IMPORTANT: We do NOT define this struct in Rust. Instead, we receive
/// `*mut k_sem` from C and access fields through accessor functions or
/// offset-based access. This is because the exact layout is config-dependent.
///
/// For the POC, we define accessor helpers that would be generated by bindgen
/// in production. The offsets shown are for a minimal config (no POLL, no OBJ_CORE).
#[repr(C)]
pub struct k_sem {
    /// Wait queue for blocked threads.
    pub wait_q: _wait_q_t,
    /// Current available count.
    pub count: u32,
    /// Maximum count (upper bound).
    pub limit: u32,
    // Note: In a real build, Z_DECL_POLL_EVENT and other conditional
    // fields would follow. Bindgen handles this automatically.
}

// ---------------------------------------------------------------------------
// Zephyr kernel scheduler functions (extern "C")
// ---------------------------------------------------------------------------
//
// These are the kernel-internal functions that gale_sem.c calls.
// In the full-Rust replacement, we call them directly via FFI.
//
// Source: ${ZEPHYR_BASE}/kernel/include/ksched.h

unsafe extern "C" {
    /// Remove and return the highest-priority thread from a wait queue.
    ///
    /// Returns NULL if the queue is empty.
    ///
    /// C signature (ksched.h:162):
    ///   static ALWAYS_INLINE struct k_thread *z_unpend_first_thread(_wait_q_t *wait_q);
    ///
    /// Note: This is an inline function in Zephyr. For FFI, we either:
    ///   a) Create a thin C wrapper that calls it (easiest), or
    ///   b) Re-implement the logic in Rust (requires _priq_wait_best binding).
    /// The POC assumes option (a) — a C trampoline.
    pub fn z_unpend_first_thread(wait_q: *mut _wait_q_t) -> *mut k_thread;

    /// Block the current thread on a wait queue with timeout.
    ///
    /// This is the core "pend" operation: the calling thread is suspended
    /// and placed on the wait queue. The spinlock is released atomically
    /// with the context switch.
    ///
    /// Returns 0 on success (thread was woken), or negative errno on timeout/error.
    ///
    /// C signature (ksched.h:58-59):
    ///   int z_pend_curr(struct k_spinlock *lock, k_spinlock_key_t key,
    ///                   _wait_q_t *wait_q, k_timeout_t timeout);
    pub fn z_pend_curr(
        lock: *mut k_spinlock,
        key: k_spinlock_key_t,
        wait_q: *mut _wait_q_t,
        timeout: k_timeout_t,
    ) -> i32;

    /// Mark a thread as ready to run.
    ///
    /// After unpending a thread, this makes it schedulable again.
    ///
    /// C signature (ksched.h:72):
    ///   void z_ready_thread(struct k_thread *thread);
    pub fn z_ready_thread(thread: *mut k_thread);

    /// Set the return value that a thread will see when it resumes.
    ///
    /// Used to pass 0 (success) or -EAGAIN (reset) to woken threads.
    ///
    /// C signature (kernel_arch_interface.h:160):
    ///   static inline void arch_thread_return_value_set(
    ///       struct k_thread *thread, unsigned int value);
    ///
    /// Note: Also an inline — needs C trampoline or re-implementation.
    pub fn arch_thread_return_value_set(thread: *mut k_thread, value: u32);

    /// Reschedule after modifying the ready queue.
    ///
    /// If a higher-priority thread was readied, this triggers a context switch.
    /// Releases the spinlock as part of the reschedule.
    ///
    /// C signature (ksched.h:62):
    ///   void z_reschedule(struct k_spinlock *lock, k_spinlock_key_t key);
    pub fn z_reschedule(lock: *mut k_spinlock, key: k_spinlock_key_t);

    /// Acquire a spinlock, disabling interrupts.
    ///
    /// Returns the previous interrupt state (key) for later restoration.
    ///
    /// C signature (spinlock.h):
    ///   static ALWAYS_INLINE k_spinlock_key_t k_spin_lock(struct k_spinlock *l);
    ///
    /// Note: Inline — needs C trampoline.
    pub fn k_spin_lock(lock: *mut k_spinlock) -> k_spinlock_key_t;

    /// Release a spinlock, restoring interrupt state.
    ///
    /// C signature (spinlock.h):
    ///   static ALWAYS_INLINE void k_spin_unlock(struct k_spinlock *l, k_spinlock_key_t key);
    ///
    /// Note: Inline — needs C trampoline.
    pub fn k_spin_unlock(lock: *mut k_spinlock, key: k_spinlock_key_t);

    /// Initialize a wait queue.
    ///
    /// C signature (wait_q.h:40):
    ///   static inline void z_waitq_init(_wait_q_t *w);
    pub fn z_waitq_init(wait_q: *mut _wait_q_t);

    /// Initialize a kernel object for userspace tracking.
    ///
    /// C signature (syscall_handler.h):
    ///   void k_object_init(const void *obj);
    pub fn k_object_init(obj: *const c_void);

    /// Handle poll events (CONFIG_POLL only).
    ///
    /// C signature (kernel_internal.h:186):
    ///   bool z_handle_obj_poll_events(sys_dlist_t *events, uint32_t state);
    ///
    /// We conditionally call this; if CONFIG_POLL is disabled, we skip it.
    pub fn z_handle_obj_poll_events(events: *mut c_void, state: u32) -> bool;
}

// ---------------------------------------------------------------------------
// Constants matching Zephyr kernel defines
// ---------------------------------------------------------------------------

/// K_POLL_STATE_SEM_AVAILABLE — used with z_handle_obj_poll_events.
pub const K_POLL_STATE_SEM_AVAILABLE: u32 = 0x02; // BIT(1) in Zephyr
