// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified condition variable for Zephyr RTOS.
//
// This is a formally verified port of zephyr/kernel/condvar.c.
// All safety-critical properties are proven with Verus (SMT/Z3).
//
// Source mapping:
//   z_impl_k_condvar_init      -> CondVar::init          (condvar.c:21-30)
//   z_impl_k_condvar_signal    -> CondVar::signal         (condvar.c:44-61)
//   z_impl_k_condvar_broadcast -> CondVar::broadcast      (condvar.c:73-96)
//   z_impl_k_condvar_wait      -> CondVar::wait_blocking  (condvar.c:99-121)
//
// Omitted (not safety-relevant):
//   - CONFIG_OBJ_CORE_CONDVAR — debug/tracing
//   - CONFIG_USERSPACE (z_vrfy_*) — syscall marshaling
//   - SYS_PORT_TRACING_* — instrumentation
//   - Timeout handling (modeled as immediate blocking)
//
// ASIL-D verified properties:
//   C1: After init, wait queue is empty
//   C2: Signal wakes at most one waiter (highest priority)
//   C3: Signal on empty condvar is a no-op
//   C4: Broadcast wakes all waiters, returns woken count
//   C5: Broadcast on empty condvar returns 0
//   C6: Wait adds thread to wait queue (blocking path)
//   C7: Signal/broadcast preserve wait queue ordering
//   C8: No arithmetic overflow in broadcast woken count
/// Result of a signal operation.
#[derive(Debug)]
pub enum SignalResult {
    /// No thread was waiting — signal was a no-op.
    Empty,
    /// The highest-priority waiting thread was woken.
    Woke(Thread),
}
/// Condition variable — port of Zephyr kernel/condvar.c.
///
/// Corresponds to Zephyr's struct k_condvar {
///     _wait_q_t wait_q;
/// };
///
/// A condvar is a pure wait queue. Threads wait on it (releasing a held
/// mutex atomically), and are woken by signal (one) or broadcast (all).
pub struct CondVar {
    /// Wait queue for threads blocked on this condvar.
    pub wait_q: WaitQueue,
}
impl CondVar {
    /// Initialize a condition variable.
    ///
    /// ```c
    /// int z_impl_k_condvar_init(struct k_condvar *condvar)
    /// {
    ///     z_waitq_init(&condvar->wait_q);
    ///     return 0;
    /// }
    /// ```
    ///
    /// Verified properties:
    /// - Establishes the invariant (C1)
    /// - Wait queue starts empty
    pub fn init() -> Self {
        CondVar {
            wait_q: WaitQueue::new(),
        }
    }
    /// Signal the condition variable — wake one waiter.
    ///
    /// ```c
    /// int z_impl_k_condvar_signal(struct k_condvar *condvar)
    /// {
    ///     struct k_thread *thread = z_unpend_first_thread(&condvar->wait_q);
    ///     if (thread != NULL) {
    ///         arch_thread_return_value_set(thread, 0);
    ///         z_ready_thread(thread);
    ///     }
    ///     return 0;
    /// }
    /// ```
    ///
    /// Verified properties (C2, C3, C7):
    /// - If waiters exist: highest-priority thread woken (C2)
    /// - If no waiters: no-op (C3)
    /// - Wait queue ordering preserved (C7)
    /// - Invariant maintained
    pub fn signal(&mut self) -> SignalResult {
        let thread = self.wait_q.unpend_first(OK);
        match thread {
            Some(t) => SignalResult::Woke(t),
            None => SignalResult::Empty,
        }
    }
    /// Broadcast the condition variable — wake all waiters.
    ///
    /// ```c
    /// int z_impl_k_condvar_broadcast(struct k_condvar *condvar)
    /// {
    ///     int woken = 0;
    ///     for (pending = z_unpend_first_thread(&condvar->wait_q);
    ///          pending != NULL;
    ///          pending = z_unpend_first_thread(&condvar->wait_q)) {
    ///         woken++;
    ///         arch_thread_return_value_set(pending, 0);
    ///         z_ready_thread(pending);
    ///     }
    ///     return woken;
    /// }
    /// ```
    ///
    /// Verified properties (C4, C5, C8):
    /// - All waiters woken with return value 0 (C4)
    /// - Returns count of woken threads (C4)
    /// - Empty condvar returns 0 (C5)
    /// - No overflow in woken count (C8 — bounded by MAX_WAITERS=64)
    /// - Wait queue empty after broadcast
    /// - Invariant maintained
    pub fn broadcast(&mut self) -> u32 {
        self.wait_q.unpend_all(OK)
    }
    /// Wait on the condition variable — blocking path.
    ///
    /// Models the blocking portion of k_condvar_wait:
    ///   1. The caller releases the mutex (done by C caller before this)
    ///   2. The thread is added to the condvar's wait queue
    ///   3. On wakeup, the caller re-acquires the mutex (done by C caller)
    ///
    /// ```c
    /// int z_impl_k_condvar_wait(struct k_condvar *condvar,
    ///                           struct k_mutex *mutex,
    ///                           k_timeout_t timeout)
    /// {
    ///     k_mutex_unlock(mutex);
    ///     ret = z_pend_curr(&lock, key, &condvar->wait_q, timeout);
    ///     if (ret == 0) { k_mutex_lock(mutex, K_FOREVER); }
    ///     return ret;
    /// }
    /// ```
    ///
    /// Verified properties (C6, C7):
    /// - Thread added to wait queue in priority order (C6, C7)
    /// - Thread state set to Blocked
    /// - Returns false if wait queue is full
    pub fn wait_blocking(&mut self, mut thread: Thread) -> bool {
        thread.block();
        self.wait_q.pend(thread)
    }
    /// Get the number of threads waiting on this condvar.
    pub fn num_waiters(&self) -> u32 {
        self.wait_q.len()
    }
    /// Check if any threads are waiting.
    pub fn has_waiters(&self) -> bool {
        self.wait_q.len() > 0
    }
}
/// Signal decision — what the C shim should do on k_condvar_signal.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum SignalAction {
    /// No waiter in the queue — signal is a no-op.
    Noop = 0,
    /// Wake the highest-priority waiter.
    WakeOne = 1,
}
/// Decide the action for k_condvar_signal from a scalar has_waiter flag.
///
/// Verified: C2 (wakes at most one), C3 (no-op when empty).
pub fn signal_decide(has_waiter: bool) -> SignalAction {
    if has_waiter { SignalAction::WakeOne } else { SignalAction::Noop }
}
/// Decide the action for k_condvar_broadcast.
///
/// Returns the number of waiters to wake. Pass-through, but verified
/// free of overflow (C8): the C side guarantees num_waiters fits u32.
pub fn broadcast_decide(num_waiters: u32) -> u32 {
    num_waiters
}
/// Wait decision — what the C shim should do on k_condvar_wait.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum WaitAction {
    /// Pend the current thread on the wait queue.
    Pend = 0,
    /// K_NO_WAIT timeout — return -EAGAIN without blocking.
    ReturnEagain = 1,
}
/// Decide the action for k_condvar_wait from a scalar is_no_wait flag.
///
/// Verified: C6 (blocking path adds thread to wait queue; non-blocking
/// path returns EAGAIN immediately).
pub fn wait_decide(is_no_wait: bool) -> WaitAction {
    if is_no_wait { WaitAction::ReturnEagain } else { WaitAction::Pend }
}