// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified fatal error model for Zephyr RTOS.
//
// This is a formally verified model of Zephyr's fatal error handling
// from kernel/fatal.c. All safety-critical properties are proven
// with Verus (SMT/Z3).
//
// This module models the **fault classification and recovery decision**
// logic of Zephyr's fatal error subsystem. Actual error handling
// (IRQ lock, coredump, thread abort) remains in C.
//
// Source mapping:
//   K_ERR_*                -> FatalReason enum       (fatal.h)
//   reason_to_str          -> FatalReason::as_str     (fatal.c:60-76)
//   z_fatal_error          -> FatalError::classify    (fatal.c:85-179)
//   k_fatal_halt           -> (not modeled — halts)  (fatal.c:79-82)
//   k_sys_fatal_error_handler -> (not modeled — app) (fatal.c:37-46)
//
// Omitted (not safety-relevant):
//   - SYS_PORT_TRACING_* — instrumentation
//   - CONFIG_ARCH_HAS_NESTED_EXCEPTION_DETECTION — arch-specific ISR nesting
//   - CONFIG_STACK_SENTINEL — stack guard variant
//   - coredump() — diagnostic data capture
//   - thread_name_get() — debug string lookup
//   - arch_system_halt() — hardware halt sequence
//
// ASIL-D verified properties:
//   FT1: all reason codes map to a valid FatalReason variant
//   FT2: kernel panic is always non-recoverable
//   FT3: recoverable decision depends on reason and context
//   FT4: reason codes are distinct (no overlap)
/// Fatal error reason codes — matches zephyr/include/zephyr/fatal.h K_ERR_*.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FatalReason {
    /// CPU exception (e.g., invalid instruction, bus fault).
    CpuException,
    /// Unhandled / spurious interrupt.
    SpuriousIrq,
    /// Stack overflow detected (guard or sentinel).
    StackCheckFail,
    /// Kernel oops (assertion failure in kernel code).
    KernelOops,
    /// Kernel panic (unrecoverable — system must halt).
    KernelPanic,
}
/// Execution context at the time of the fatal error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FatalContext {
    /// Fault occurred in thread context.
    Thread,
    /// Fault occurred in ISR (interrupt service routine) context.
    Isr,
}
/// Recovery action determined by the fatal error handler.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecoveryAction {
    /// Abort the faulting thread and continue.
    AbortThread,
    /// Halt the entire system (no recovery possible).
    Halt,
    /// In test mode, return without action (for ISR-context spurious IRQs).
    Ignore,
}
/// Fatal error classification model.
///
/// Encapsulates a fatal error event with its reason, context, and
/// whether we are in test mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FatalError {
    /// The error reason code.
    pub reason: FatalReason,
    /// Whether the fault occurred in thread or ISR context.
    pub context: FatalContext,
    /// Whether CONFIG_TEST is enabled.
    pub test_mode: bool,
}
impl FatalError {
    /// Create a fatal error event.
    pub fn new(
        reason: FatalReason,
        context: FatalContext,
        test_mode: bool,
    ) -> FatalError {
        FatalError {
            reason,
            context,
            test_mode,
        }
    }
    /// Determine the recovery action for this fatal error.
    ///
    /// Models the decision logic in z_fatal_error() (fatal.c:85-179).
    ///
    /// FT2: kernel panic always halts.
    /// FT3: recovery depends on reason, context, and test mode.
    pub fn classify(&self) -> RecoveryAction {
        if matches!(self.reason, FatalReason::KernelPanic) {
            return RecoveryAction::Halt;
        }
        if !self.test_mode {
            match self.reason {
                FatalReason::KernelPanic => RecoveryAction::Halt,
                FatalReason::CpuException => {
                    match self.context {
                        FatalContext::Isr => RecoveryAction::Halt,
                        FatalContext::Thread => RecoveryAction::AbortThread,
                    }
                }
                FatalReason::SpuriousIrq => {
                    match self.context {
                        FatalContext::Isr => RecoveryAction::Halt,
                        FatalContext::Thread => RecoveryAction::AbortThread,
                    }
                }
                FatalReason::StackCheckFail => RecoveryAction::AbortThread,
                FatalReason::KernelOops => {
                    match self.context {
                        FatalContext::Isr => RecoveryAction::Halt,
                        FatalContext::Thread => RecoveryAction::AbortThread,
                    }
                }
            }
        } else {
            match self.context {
                FatalContext::Isr => {
                    match self.reason {
                        FatalReason::SpuriousIrq => RecoveryAction::Ignore,
                        FatalReason::StackCheckFail => RecoveryAction::AbortThread,
                        FatalReason::CpuException => RecoveryAction::Ignore,
                        FatalReason::KernelOops => RecoveryAction::Ignore,
                        FatalReason::KernelPanic => RecoveryAction::Halt,
                    }
                }
                FatalContext::Thread => RecoveryAction::AbortThread,
            }
        }
    }
    /// Map a numeric reason code to FatalReason.
    ///
    /// Models the implicit mapping in z_fatal_error / reason_to_str.
    /// FT1: all valid codes produce a valid variant.
    pub fn from_code(code: u32) -> Option<FatalReason> {
        match code {
            0 => Some(FatalReason::CpuException),
            1 => Some(FatalReason::SpuriousIrq),
            2 => Some(FatalReason::StackCheckFail),
            3 => Some(FatalReason::KernelOops),
            4 => Some(FatalReason::KernelPanic),
            _ => None,
        }
    }
    /// Get a reason description string.
    ///
    /// Models reason_to_str() (fatal.c:60-76).
    pub fn reason_str(reason: FatalReason) -> &'static str {
        match reason {
            FatalReason::CpuException => "CPU exception",
            FatalReason::SpuriousIrq => "Unhandled interrupt",
            FatalReason::StackCheckFail => "Stack overflow",
            FatalReason::KernelOops => "Kernel oops",
            FatalReason::KernelPanic => "Kernel panic",
        }
    }
    /// Check if the reason is a kernel panic.
    pub fn is_panic(&self) -> bool {
        matches!(self.reason, FatalReason::KernelPanic)
    }
    /// Check if the error occurred in ISR context.
    pub fn is_isr(&self) -> bool {
        matches!(self.context, FatalContext::Isr)
    }
}
/// Decision for fatal error classification from numeric arguments.
///
/// FT1: maps reason codes. FT2: panic halts. FT3: recovery depends on context.
/// Returns Ok(RecoveryAction) or Err(EINVAL) for unknown reason.
pub fn classify_decide(
    reason: u32,
    is_isr: bool,
    test_mode: bool,
) -> Result<RecoveryAction, i32> {
    match FatalError::from_code(reason) {
        Some(r) => {
            let err = FatalError::new(
                r,
                if is_isr { FatalContext::Isr } else { FatalContext::Thread },
                test_mode,
            );
            Ok(err.classify())
        }
        None => Err(EINVAL),
    }
}