// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified memory slab allocator for Zephyr RTOS.
//
// This is a formally verified port of zephyr/kernel/mem_slab.c.
// All safety-critical properties are proven with Verus (SMT/Z3).
//
// This module models the **block allocation counter** of Zephyr's mem_slab
// object.  Actual free-list pointer management and memory storage remain
// in C — only the block count tracking crosses the FFI boundary.
//
// Source mapping:
//   k_mem_slab_init      -> MemSlab::init      (mem_slab.c)
//   k_mem_slab_alloc     -> MemSlab::alloc     (mem_slab.c, availability check + increment)
//   k_mem_slab_free      -> MemSlab::free      (mem_slab.c, decrement)
//   k_mem_slab_num_used_get  -> MemSlab::num_used_get
//   k_mem_slab_num_free_get  -> MemSlab::num_free_get
//
// Omitted (not safety-relevant):
//   - CONFIG_OBJ_CORE_MEM_SLAB — debug/tracing
//   - CONFIG_USERSPACE (z_vrfy_*) — syscall marshaling
//   - SYS_PORT_TRACING_* — instrumentation
//   - k_mem_slab_runtime_stats_* — statistics
//
// ASIL-D verified properties:
//   MS1: 0 <= num_used <= num_blocks (bounds invariant)
//   MS2: num_blocks > 0 after init
//   MS3: block_size > 0 after init
//   MS4: alloc when num_used < num_blocks: num_used += 1, returns OK
//   MS5: alloc when num_used == num_blocks: returns ENOMEM, unchanged
//   MS6: free when num_used > 0: num_used -= 1, returns OK
//   MS7: num_free + num_used == num_blocks (conservation)
//   MS8: no arithmetic overflow in any operation
/// Memory slab allocator — block count model.
///
/// Corresponds to Zephyr's struct k_mem_slab {
///     uint32_t num_blocks;   // total blocks
///     size_t   block_size;   // bytes per block
///     uint32_t num_used;     // currently allocated
///     ...                    // free_list, buffer (in C)
/// };
///
/// We model the counter: num_used tracks allocated blocks.
/// The C shim manages the actual free-list pointers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MemSlab {
    /// Total number of blocks (immutable after init).
    pub num_blocks: u32,
    /// Size of each block in bytes (immutable after init).
    pub block_size: u32,
    /// Number of currently allocated blocks.
    pub num_used: u32,
}
impl MemSlab {
    /// Initialize a memory slab with given block_size and num_blocks.
    ///
    /// Returns EINVAL if block_size == 0 or num_blocks == 0.
    pub fn init(block_size: u32, num_blocks: u32) -> Result<MemSlab, i32> {
        if block_size == 0 || num_blocks == 0 {
            Err(EINVAL)
        } else {
            Ok(MemSlab {
                num_blocks,
                block_size,
                num_used: 0,
            })
        }
    }
    /// Allocate a block from the slab.
    ///
    /// Returns OK (num_used incremented) or ENOMEM (full, unchanged).
    pub fn alloc(&mut self) -> i32 {
        if self.num_used >= self.num_blocks {
            ENOMEM
        } else {
            #[allow(clippy::arithmetic_side_effects)]
            {
                self.num_used = self.num_used + 1;
            }
            OK
        }
    }
    /// Free a block back to the slab.
    ///
    /// Returns OK (num_used decremented) or EINVAL (all blocks already free).
    pub fn free(&mut self) -> i32 {
        if self.num_used == 0 {
            EINVAL
        } else {
            #[allow(clippy::arithmetic_side_effects)]
            {
                self.num_used = self.num_used - 1;
            }
            OK
        }
    }
    /// Number of currently allocated blocks.
    pub fn num_used_get(&self) -> u32 {
        self.num_used
    }
    /// Number of free (available) blocks.
    pub fn num_free_get(&self) -> u32 {
        #[allow(clippy::arithmetic_side_effects)]
        let r = self.num_blocks - self.num_used;
        r
    }
    /// Total number of blocks.
    pub fn num_blocks_get(&self) -> u32 {
        self.num_blocks
    }
    /// Size of each block in bytes.
    pub fn block_size_get(&self) -> u32 {
        self.block_size
    }
    /// Check if slab is full (all blocks allocated).
    pub fn is_full(&self) -> bool {
        self.num_used == self.num_blocks
    }
    /// Check if slab is empty (no blocks allocated).
    pub fn is_empty(&self) -> bool {
        self.num_used == 0
    }
}
/// Lightweight alloc decision — no MemSlab allocation.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum AllocDecision {
    /// Block available: num_used incremented.
    Alloc = 0,
    /// Slab full, willing to wait: pend current thread.
    Pend = 1,
    /// Slab full, no-wait: return immediately.
    NoMem = 2,
}
/// Result of an alloc decision with updated count.
#[derive(Debug)]
pub struct AllocDecideResult {
    pub decision: AllocDecision,
    pub new_num_used: u32,
}
/// Lightweight free decision — no MemSlab allocation.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum FreeDecision {
    /// Block returned to free list: num_used decremented.
    Free = 0,
    /// A waiter exists: give block directly to waiting thread (count unchanged).
    WakeThread = 1,
}
/// Result of a free decision with updated count.
#[derive(Debug)]
pub struct FreeDecideResult {
    pub decision: FreeDecision,
    pub new_num_used: u32,
}
/// Lightweight alloc decision — takes scalars, no MemSlab allocation.
///
/// Verified properties (MS4, MS5, MS1):
/// - num_used < num_blocks ==> Alloc (num_used + 1)
/// - num_used >= num_blocks && is_no_wait ==> NoMem
/// - num_used >= num_blocks && !is_no_wait ==> Pend
pub fn alloc_decide(
    num_used: u32,
    num_blocks: u32,
    is_no_wait: bool,
) -> AllocDecideResult {
    if num_used < num_blocks {
        AllocDecideResult {
            decision: AllocDecision::Alloc,
            new_num_used: num_used + 1,
        }
    } else if is_no_wait {
        AllocDecideResult {
            decision: AllocDecision::NoMem,
            new_num_used: num_used,
        }
    } else {
        AllocDecideResult {
            decision: AllocDecision::Pend,
            new_num_used: num_used,
        }
    }
}
/// Lightweight free decision — takes scalars, no MemSlab allocation.
///
/// Verified properties (MS6, MS1):
/// - has_waiter ==> WakeThread (count unchanged)
/// - !has_waiter && num_used > 0 ==> Free (count - 1)
/// - !has_waiter && num_used == 0 ==> Free (count unchanged, no-op)
pub fn free_decide(num_used: u32, has_waiter: bool) -> FreeDecideResult {
    if has_waiter {
        FreeDecideResult {
            decision: FreeDecision::WakeThread,
            new_num_used: num_used,
        }
    } else if num_used > 0 {
        FreeDecideResult {
            decision: FreeDecision::Free,
            new_num_used: num_used - 1,
        }
    } else {
        FreeDecideResult {
            decision: FreeDecision::Free,
            new_num_used: 0,
        }
    }
}