// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified ARM MPU v7 region validation model.
//
// This is a formally verified model of the ARMv7-M Memory Protection Unit
// region configuration constraints, based on Zephyr's MPU driver code in
// `arch/arm/core/mpu/arm_mpu_v7_internal.h`.
//
// Source mapping:
//   mpu_partition_is_valid   -> validate_region     (arm_mpu_v7_internal.h:63-78)
//   arm_mpu_region struct    -> MpuRegion           (arm_mpu.h:39-50)
//   mpu_configure_regions    -> validate_region_set (arm_mpu.c:215-246)
//
// ARM MPU v7 hardware constraints:
//   - Region size must be a power of 2
//   - Region size must be >= 32 bytes (CONFIG_ARM_MPU_REGION_MIN_ALIGN_AND_SIZE)
//   - Region base address must be aligned to its size: (base & (size - 1)) == 0
//   - Maximum 8 regions on Cortex-M0+/M3/M4, 16 on Cortex-M7
//
// ASIL-D verified properties:
//   P1: validate_region accepts only power-of-2 sizes >= 32, aligned bases
//   P2: regions_overlap correctly detects address range intersection
//   P3: validate_region_set rejects any configuration with overlapping regions
//   P4: no arithmetic overflow in any operation (u32 range)
/// Minimum MPU region size in bytes (CONFIG_ARM_MPU_REGION_MIN_ALIGN_AND_SIZE).
/// This is 32 bytes for ARMv7-M, matching the hardware minimum.
pub const MIN_REGION_SIZE: u32 = 32;
/// Maximum number of MPU regions (Cortex-M0+/M3/M4).
pub const MAX_REGIONS_V7: u32 = 8;
/// Maximum number of MPU regions (Cortex-M7/ARMv8-M).
pub const MAX_REGIONS_V8: u32 = 16;
/// An MPU region configuration.
///
/// Corresponds to Zephyr's `struct arm_mpu_region`:
/// ```c
/// struct arm_mpu_region {
///     uint32_t base;
///     arm_mpu_region_attr_t attr;
/// };
/// ```
///
/// The size is encoded in the RASR register in hardware, but we model
/// it explicitly for clarity.
#[derive(Clone, Copy)]
pub struct MpuRegion {
    /// Region base address. Must be aligned to `size`.
    pub base: u32,
    /// Region size in bytes. Must be a power of 2, >= 32.
    pub size: u32,
    /// Region attributes (access permissions, cache policy, XN bit).
    /// Encoded as the RASR register value (excluding size/enable fields).
    pub attr: u32,
}
/// Check if a value is a power of 2.
///
/// Mirrors the C idiom: `(n & (n - 1)) == 0` with `n > 0`.
/// This is the exact check used in `mpu_partition_is_valid()`.
///
/// The ensures uses the spec-level characterisation (is_pow2_spec) to
/// avoid bitwise AND in spec context.  The body uses the standard C
/// idiom which is valid in exec context.
///
/// Proof strategy: `by(bit_vector)` establishes that `n > 0 && n & (n-1) == 0`
/// iff `n` is one of the 32 known powers of two (matching the flat
/// enumeration in is_pow2_spec).  No recursive unfolding needed.
pub fn is_power_of_two(n: u32) -> bool {
    let result = n > 0 && (n & (n - 1)) == 0;
    result
}
/// Validate a single MPU region configuration.
///
/// Mirrors `mpu_partition_is_valid()` from arm_mpu_v7_internal.h:63-78:
/// ```c
/// int partition_is_valid =
///     ((part->size & (part->size - 1U)) == 0U)
///     &&
///     (part->size >= CONFIG_ARM_MPU_REGION_MIN_ALIGN_AND_SIZE)
///     &&
///     ((part->start & (part->size - 1U)) == 0U);
/// ```
///
/// Returns true if and only if:
/// - `size` is a power of 2 (size & (size-1) == 0, size > 0)
/// - `size` >= MIN_REGION_SIZE (32 bytes)
/// - `base` is aligned to `size` (base & (size-1) == 0)
/// - `base + size` does not overflow u32 (UCA U-6): each field alone
///   can pass alignment / power-of-two / minimum-size checks while the
///   pair sum wraps (e.g. base=0x8000_0000, size=0x8000_0000 wraps to
///   0), violating regions_overlap's `requires` clause and silently
///   defeating userspace isolation in release builds.
pub fn validate_region(base: u32, size: u32) -> bool {
    if size == 0 {
        return false;
    }
    let power_of_two = (size & (size - 1)) == 0;
    let min_size = size >= MIN_REGION_SIZE;
    let aligned = (base & (size - 1)) == 0;
    let no_overflow = base.checked_add(size).is_some();
    power_of_two && min_size && aligned && no_overflow
}
/// Check whether two MPU regions overlap in the address space.
///
/// Two regions overlap if their address ranges [base, base+size) intersect.
/// This is a pure function — no side effects, no overflow risk because we
/// use careful comparison ordering.
///
/// For two intervals [a, a+sa) and [b, b+sb):
///   overlap iff a < b+sb AND b < a+sa
///
/// We must handle the u32 addition carefully to avoid overflow.
/// If base + size would overflow u32, we treat the end as u32::MAX + 1
/// (the region wraps the address space), which we model by checking
/// separately.
pub fn regions_overlap(r1: &MpuRegion, r2: &MpuRegion) -> bool {
    let r1_end = r1.base + r1.size;
    let r2_end = r2.base + r2.size;
    r1.base < r2_end && r2.base < r1_end
}
/// Validate a set of MPU regions: each region must be individually valid,
/// and no two regions may overlap.
///
/// Mirrors the coherence check in `mpu_configure_regions()` (arm_mpu.c:215-246)
/// which calls `mpu_partition_is_valid()` on each region.
///
/// The pairwise non-overlap check models the ARMv7-M requirement that
/// region matching is deterministic: overlapping regions with different
/// attributes would cause unpredictable behavior.
///
/// `count` specifies how many entries in `regions` to validate.
///
/// U-6 / CC-6: this function remains `external_body` (the loop-invariant
/// proof that every pair satisfies `regions_overlap`'s precondition is
/// left to a follow-up), but each call to `regions_overlap` below is
/// now guarded by a runtime `checked_add` precondition check that
/// short-circuits to `false` on overflow.  Combined with
/// `validate_region`'s own overflow check (which already rejects any
/// region with base + size > u32::MAX before the pair loop runs), this
/// makes it impossible for `regions_overlap` to be called with a
/// precondition violation — even if an attacker crafts a region set
/// where individual fields look innocuous.
pub fn validate_region_set(regions: &[MpuRegion], count: u32) -> bool {
    let mut i: u32 = 0;
    while i < count {
        let r = &regions[i as usize];
        if !validate_region(r.base, r.size) {
            return false;
        }
        i = i + 1;
    }
    let mut i2: u32 = 0;
    while i2 < count {
        let mut j: u32 = 0;
        while j < count {
            if i2 != j {
                let ri = &regions[i2 as usize];
                let rj = &regions[j as usize];
                if ri.base.checked_add(ri.size).is_none()
                    || rj.base.checked_add(rj.size).is_none()
                {
                    return false;
                }
                if regions_overlap(ri, rj) {
                    return false;
                }
            }
            j = j + 1;
        }
        i2 = i2 + 1;
    }
    true
}