// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified message queue for Zephyr RTOS.
//
// This is a formally verified port of zephyr/kernel/msg_q.c.
// All safety-critical properties are proven with Verus (SMT/Z3).
//
// This module models the **ring buffer index arithmetic** of Zephyr's
// message queue.  Actual message data and wait queue management remain
// in C — only the index computation crosses the FFI boundary.
//
// Source mapping:
//   k_msgq_init      -> MsgQ::init         (msg_q.c:43-71)
//   k_msgq_put       -> MsgQ::put          (msg_q.c:130-228, ring buffer path)
//   k_msgq_put_front -> MsgQ::put_front    (msg_q.c:236-239)
//   k_msgq_get       -> MsgQ::get          (msg_q.c:280-349, ring buffer path)
//   k_msgq_peek_at   -> MsgQ::peek_at      (msg_q.c:397-430)
//   k_msgq_purge     -> MsgQ::purge        (msg_q.c:443-470, index reset)
//   k_msgq_num_free  -> MsgQ::num_free_get (kernel.h inline)
//   k_msgq_num_used  -> MsgQ::num_used_get (kernel.h inline)
//
// Omitted (not safety-relevant):
//   - CONFIG_POLL (poll_events) — application convenience
//   - CONFIG_OBJ_CORE_MSGQ — debug/tracing
//   - CONFIG_USERSPACE (z_vrfy_*) — syscall marshaling
//   - SYS_PORT_TRACING_* — instrumentation
//   - k_msgq_alloc_init — heap allocation wrapper
//   - k_msgq_cleanup — deallocation
//
// ASIL-D verified properties:
//   MQ1:  0 <= used_msgs <= max_msgs (capacity invariant)
//   MQ2:  read_idx < max_msgs (index bounds)
//   MQ3:  write_idx < max_msgs (index bounds)
//   MQ4:  msg_size > 0, max_msgs > 0 (always)
//   MQ5:  put on non-full queue: used_msgs incremented, write_idx advanced
//   MQ6:  put on full queue: returns ENOMSG, state unchanged
//   MQ7:  put_front on non-full queue: read_idx retreated correctly
//   MQ8:  get on non-empty queue: used_msgs decremented, read_idx advanced
//   MQ9:  get on empty queue: returns ENOMSG, state unchanged
//   MQ10: peek_at computes correct slot index
//   MQ11: purge resets to empty (used_msgs=0, read_idx=write_idx)
//   MQ12: no arithmetic overflow in any operation
//   MQ13: ring buffer consistency: write_idx tracks read_idx + used_msgs
/// Result of a put/get operation.
pub enum MsgQResult {
    /// Operation succeeded — indices updated.
    Ok,
    /// Queue full (put) or empty (get).
    Full,
}
/// Message queue — ring buffer index model.
///
/// Corresponds to Zephyr's struct k_msgq {
///     size_t msg_size;
///     uint32_t max_msgs;
///     char *buffer_start, *buffer_end;
///     char *read_ptr, *write_ptr;
///     uint32_t used_msgs;
/// };
///
/// We model read_ptr/write_ptr as slot indices (0..max_msgs-1)
/// rather than byte pointers.  The C shim converts:
///   byte_ptr = buffer_start + slot_idx * msg_size
#[derive(Debug)]
pub struct MsgQ {
    /// Size of each message in bytes (immutable after init).
    pub msg_size: u32,
    /// Maximum number of messages (immutable after init).
    pub max_msgs: u32,
    /// Current read slot index.
    pub read_idx: u32,
    /// Current write slot index.
    pub write_idx: u32,
    /// Number of messages currently in queue.
    pub used_msgs: u32,
}
impl MsgQ {
    /// Initialize a message queue.
    ///
    /// ```c
    /// void k_msgq_init(struct k_msgq *msgq, char *buffer,
    ///                  size_t msg_size, uint32_t max_msgs)
    /// {
    ///     msgq->msg_size = msg_size;
    ///     msgq->max_msgs = max_msgs;
    ///     msgq->buffer_start = buffer;
    ///     msgq->buffer_end = buffer + (max_msgs * msg_size);
    ///     msgq->read_ptr = buffer;
    ///     msgq->write_ptr = buffer;
    ///     msgq->used_msgs = 0;
    /// }
    /// ```
    ///
    /// Verified properties:
    /// - Establishes the invariant (MQ1-MQ4, MQ13)
    /// - Queue starts empty (MQ11)
    /// - Rejects msg_size=0, max_msgs=0, overflow in msg_size*max_msgs
    pub fn init(msg_size: u32, max_msgs: u32) -> Result<Self, i32> {
        if msg_size == 0 || max_msgs == 0 {
            return Err(EINVAL);
        }
        if msg_size.checked_mul(max_msgs).is_none() {
            return Err(EINVAL);
        }
        Ok(MsgQ {
            msg_size,
            max_msgs,
            read_idx: 0,
            write_idx: 0,
            used_msgs: 0,
        })
    }
    /// Advance an index by one slot, wrapping at max_msgs.
    ///
    /// msg_q.c:170-173:
    ///   write_ptr += msg_size;
    ///   if (write_ptr == buffer_end) write_ptr = buffer_start;
    fn next_idx(&self, idx: u32) -> u32 {
        if idx + 1 < self.max_msgs { idx + 1 } else { 0 }
    }
    /// Retreat an index by one slot, wrapping at max_msgs.
    ///
    /// msg_q.c:180-184:
    ///   if (read_ptr == buffer_start) read_ptr = buffer_end;
    ///   read_ptr -= msg_size;
    fn prev_idx(&self, idx: u32) -> u32 {
        if idx == 0 { self.max_msgs - 1 } else { idx - 1 }
    }
    /// Put a message at the back of the queue (ring buffer index update).
    ///
    /// ```c
    /// // msg_q.c:164-173 (put_at_back path, no pending thread)
    /// memcpy(msgq->write_ptr, data, msgq->msg_size);
    /// msgq->write_ptr += msgq->msg_size;
    /// if (msgq->write_ptr == msgq->buffer_end) {
    ///     msgq->write_ptr = msgq->buffer_start;
    /// }
    /// msgq->used_msgs++;
    /// ```
    ///
    /// Returns the write slot index where the message should be placed.
    /// The C shim does the memcpy at buffer_start + slot * msg_size.
    ///
    /// Verified properties (MQ5, MQ6, MQ12, MQ13):
    /// - If not full: write_idx advanced, used_msgs incremented
    /// - If full: returns error, state unchanged
    /// - No overflow in index arithmetic
    /// - Ring buffer consistency maintained
    pub fn put(&mut self) -> Result<u32, i32> {
        if self.used_msgs >= self.max_msgs {
            return Err(ENOMSG);
        }
        let slot = self.write_idx;
        self.write_idx = self.next_idx(self.write_idx);
        self.used_msgs = self.used_msgs + 1;
        Ok(slot)
    }
    /// Put a message at the front of the queue (ring buffer index update).
    ///
    /// ```c
    /// // msg_q.c:174-186 (put_at_front path)
    /// if (msgq->read_ptr == msgq->buffer_start) {
    ///     msgq->read_ptr = msgq->buffer_end;
    /// }
    /// msgq->read_ptr -= msgq->msg_size;
    /// memcpy(msgq->read_ptr, data, msgq->msg_size);
    /// msgq->used_msgs++;
    /// ```
    ///
    /// Returns the read slot index where the message should be placed.
    ///
    /// Verified properties (MQ7, MQ12, MQ13):
    /// - If not full: read_idx retreated, used_msgs incremented
    /// - If full: returns error, state unchanged
    /// - Ring buffer consistency maintained
    pub fn put_front(&mut self) -> Result<u32, i32> {
        if self.used_msgs >= self.max_msgs {
            return Err(ENOMSG);
        }
        self.read_idx = self.prev_idx(self.read_idx);
        self.used_msgs = self.used_msgs + 1;
        Ok(self.read_idx)
    }
    /// Get a message from the queue (ring buffer index update).
    ///
    /// ```c
    /// // msg_q.c:293-300
    /// memcpy(data, msgq->read_ptr, msgq->msg_size);
    /// msgq->read_ptr += msgq->msg_size;
    /// if (msgq->read_ptr == msgq->buffer_end) {
    ///     msgq->read_ptr = msgq->buffer_start;
    /// }
    /// msgq->used_msgs--;
    /// ```
    ///
    /// Returns the read slot index where the message is located.
    /// The C shim does the memcpy from buffer_start + slot * msg_size.
    ///
    /// Verified properties (MQ8, MQ9, MQ12, MQ13):
    /// - If not empty: read_idx advanced, used_msgs decremented
    /// - If empty: returns error, state unchanged
    /// - No underflow in used_msgs
    /// - Ring buffer consistency maintained
    pub fn get(&mut self) -> Result<u32, i32> {
        if self.used_msgs == 0 {
            return Err(ENOMSG);
        }
        let slot = self.read_idx;
        self.read_idx = self.next_idx(self.read_idx);
        self.used_msgs = self.used_msgs - 1;
        Ok(slot)
    }
    /// Compute the slot index for peeking at message `idx`.
    ///
    /// ```c
    /// // msg_q.c:408-418
    /// bytes_to_end = (msgq->buffer_end - msgq->read_ptr);
    /// byte_offset = idx * msgq->msg_size;
    /// start_addr = msgq->read_ptr;
    /// if (bytes_to_end <= byte_offset) {
    ///     byte_offset -= bytes_to_end;
    ///     start_addr = msgq->buffer_start;
    /// }
    /// memcpy(data, start_addr + byte_offset, msgq->msg_size);
    /// ```
    ///
    /// Verified properties (MQ10):
    /// - Valid index: returns correct slot
    /// - Invalid index: returns ENOMSG
    /// - No overflow in slot computation
    pub fn peek_at(&self, idx: u32) -> Result<u32, i32> {
        if idx >= self.used_msgs {
            return Err(ENOMSG);
        }
        let sum: u64 = self.read_idx as u64 + idx as u64;
        let max: u64 = self.max_msgs as u64;
        if sum < max { Ok(sum as u32) } else { Ok((sum - max) as u32) }
    }
    /// Purge the queue (reset indices).
    ///
    /// ```c
    /// // msg_q.c:462-463
    /// msgq->used_msgs = 0;
    /// msgq->read_ptr = msgq->write_ptr;
    /// ```
    ///
    /// The C shim handles waking pending threads before calling this.
    ///
    /// Verified properties (MQ11):
    /// - Queue is empty after purge
    /// - Indices are consistent
    /// - Invariant maintained
    pub fn purge(&mut self) -> u32 {
        let old_used = self.used_msgs;
        self.used_msgs = 0;
        self.read_idx = self.write_idx;
        old_used
    }
    /// Get the number of free slots.
    ///
    /// kernel.h: return msgq->max_msgs - msgq->used_msgs;
    pub fn num_free_get(&self) -> u32 {
        self.max_msgs - self.used_msgs
    }
    /// Get the number of used slots.
    pub fn num_used_get(&self) -> u32 {
        self.used_msgs
    }
    /// Get the message size.
    pub fn msg_size_get(&self) -> u32 {
        self.msg_size
    }
    /// Get the maximum message count.
    pub fn max_msgs_get(&self) -> u32 {
        self.max_msgs
    }
    /// Check if the queue is full.
    pub fn is_full(&self) -> bool {
        self.used_msgs == self.max_msgs
    }
    /// Check if the queue is empty.
    pub fn is_empty(&self) -> bool {
        self.used_msgs == 0
    }
    /// Get current read index.
    pub fn read_idx_get(&self) -> u32 {
        self.read_idx
    }
    /// Get current write index.
    pub fn write_idx_get(&self) -> u32 {
        self.write_idx
    }
}
/// Lightweight put decision — no WaitQueue allocation.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PutDecision {
    /// Space available, no waiters: store message at write_idx, advance index.
    Store = 0,
    /// Space available, waiter exists: wake a blocked reader.
    WakeReader = 1,
    /// Queue full, willing to wait: pend current thread.
    Pend = 2,
    /// Queue full, no-wait: return immediately.
    Full = 3,
}
/// Result of a put decision: the decision plus updated index/count values.
#[derive(Debug)]
pub struct PutDecideResult {
    pub decision: PutDecision,
    pub new_write_idx: u32,
    pub new_used: u32,
}
/// Lightweight get decision — no WaitQueue allocation.
#[derive(Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum GetDecision {
    /// Data available, no waiters: read from read_idx, advance index.
    Read = 0,
    /// Data available, waiter exists: also wake a blocked writer.
    WakeWriter = 1,
    /// Queue empty, willing to wait: pend current thread.
    Pend = 2,
    /// Queue empty, no-wait: return immediately.
    Empty = 3,
}
/// Result of a get decision: the decision plus updated index/count values.
#[derive(Debug)]
pub struct GetDecideResult {
    pub decision: GetDecision,
    pub new_read_idx: u32,
    pub new_used: u32,
}
/// Lightweight put decision — takes scalars, no WaitQueue allocation.
///
/// Verified properties (MQ5, MQ6, MQ12):
/// - not full && has_waiter ==> WakeReader
/// - not full && !has_waiter ==> Store (write_idx advanced, used+1)
/// - full && is_no_wait ==> Full
/// - full && !is_no_wait ==> Pend
pub fn put_decide(
    write_idx: u32,
    used_msgs: u32,
    max_msgs: u32,
    has_waiter: bool,
    is_no_wait: bool,
) -> PutDecideResult {
    if used_msgs < max_msgs {
        if has_waiter {
            PutDecideResult {
                decision: PutDecision::WakeReader,
                new_write_idx: write_idx,
                new_used: used_msgs,
            }
        } else {
            let next = if write_idx + 1 < max_msgs { write_idx + 1 } else { 0u32 };
            PutDecideResult {
                decision: PutDecision::Store,
                new_write_idx: next,
                new_used: used_msgs + 1,
            }
        }
    } else if is_no_wait {
        PutDecideResult {
            decision: PutDecision::Full,
            new_write_idx: write_idx,
            new_used: used_msgs,
        }
    } else {
        PutDecideResult {
            decision: PutDecision::Pend,
            new_write_idx: write_idx,
            new_used: used_msgs,
        }
    }
}
/// Lightweight get decision — takes scalars, no WaitQueue allocation.
///
/// Verified properties (MQ8, MQ9, MQ12):
/// - not empty: read_idx advanced, used-1
/// - not empty && has_waiter ==> WakeWriter
/// - not empty && !has_waiter ==> Read
/// - empty && is_no_wait ==> Empty
/// - empty && !is_no_wait ==> Pend
pub fn get_decide(
    read_idx: u32,
    used_msgs: u32,
    max_msgs: u32,
    has_waiter: bool,
    is_no_wait: bool,
) -> GetDecideResult {
    if used_msgs > 0 {
        let next = if read_idx + 1 < max_msgs { read_idx + 1 } else { 0u32 };
        let new_used = used_msgs - 1;
        if has_waiter {
            GetDecideResult {
                decision: GetDecision::WakeWriter,
                new_read_idx: next,
                new_used,
            }
        } else {
            GetDecideResult {
                decision: GetDecision::Read,
                new_read_idx: next,
                new_used,
            }
        }
    } else if is_no_wait {
        GetDecideResult {
            decision: GetDecision::Empty,
            new_read_idx: read_idx,
            new_used: 0,
        }
    } else {
        GetDecideResult {
            decision: GetDecision::Pend,
            new_read_idx: read_idx,
            new_used: 0,
        }
    }
}