// === Standalone stubs (generated by verus-strip --standalone) ===

// Error codes (from crate::error)
pub const OK: i32 = 0;
pub const EINVAL: i32 = -22;
pub const EAGAIN: i32 = -11;
pub const EBUSY: i32 = -16;
pub const EPERM: i32 = -1;
pub const ENOMEM: i32 = -12;
pub const ENOMSG: i32 = -42;
pub const EPIPE: i32 = -32;
pub const ECANCELED: i32 = -125;
pub const EBADF: i32 = -9;
pub const EOVERFLOW: i32 = -75;
pub const ETIMEDOUT: i32 = -110;
pub const ENOSPC: i32 = -28;
pub const ENOENT: i32 = -2;
pub const EADDRINUSE: i32 = -98;

// Priority (from crate::priority)
pub const MAX_PRIORITY: u32 = 32;

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct Priority {
    pub value: u32,
}

impl Priority {
    pub fn new(value: u32) -> Option<Self> {
        if value < MAX_PRIORITY {
            Some(Priority { value })
        } else {
            None
        }
    }
    pub fn get(&self) -> u32 {
        self.value
    }
}

// Thread types (from crate::thread)
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ThreadId {
    pub id: u32,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ThreadState {
    Ready,
    Running,
    Blocked,
    Suspended,
}

#[derive(Debug, Copy, Clone)]
pub struct Thread {
    pub id: ThreadId,
    pub priority: Priority,
    pub state: ThreadState,
    pub return_value: i32,
}

impl Thread {
    pub fn new(id: u32, priority: Priority) -> Self {
        Thread {
            id: ThreadId { id },
            priority,
            state: ThreadState::Ready,
            return_value: 0,
        }
    }
    pub fn dispatch(&mut self) {
        self.state = ThreadState::Running;
    }
    pub fn block(&mut self) {
        self.state = ThreadState::Blocked;
    }
    pub fn wake(&mut self, return_value: i32) {
        self.return_value = return_value;
        self.state = ThreadState::Ready;
    }
    pub fn is_blocked(&self) -> bool {
        matches!(self.state, ThreadState::Blocked)
    }
}

// WaitQueue (from crate::wait_queue)
pub const MAX_WAITERS: u32 = 64;

#[derive(Debug)]
pub struct WaitQueue {
    pub entries: [Option<Thread>; 64],
    pub len: u32,
}

impl WaitQueue {
    pub fn new() -> Self {
        WaitQueue {
            entries: [
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None,
            ],
            len: 0,
        }
    }
    pub fn len(&self) -> u32 {
        self.len
    }
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
    pub fn unpend_first(&mut self, return_value: i32) -> Option<Thread> {
        if self.len == 0 {
            return None;
        }
        let thread = self.entries[0];
        let mut i: u32 = 0;
        while i < self.len - 1 {
            self.entries[i as usize] = self.entries[(i + 1) as usize];
            i = i + 1;
        }
        self.entries[(self.len - 1) as usize] = None;
        self.len = self.len - 1;
        match thread {
            Some(mut t) => {
                t.state = ThreadState::Ready;
                t.return_value = return_value;
                Some(t)
            }
            None => None,
        }
    }
    pub fn pend(&mut self, thread: Thread) -> bool {
        if self.len >= MAX_WAITERS {
            return false;
        }
        let mut insert_pos: u32 = self.len;
        let mut i: u32 = 0;
        while i < self.len {
            let entry_pri = self.entries[i as usize].unwrap().priority.get();
            let thr_pri = thread.priority.get();
            if thr_pri < entry_pri {
                insert_pos = i;
                break;
            }
            i = i + 1;
        }
        let mut j: u32 = self.len;
        while j > insert_pos {
            self.entries[j as usize] = self.entries[(j - 1) as usize];
            j = j - 1;
        }
        self.entries[insert_pos as usize] = Some(thread);
        self.len = self.len + 1;
        true
    }
    pub fn unpend_all(&mut self, _return_value: i32) -> u32 {
        let count = self.len;
        let mut i: u32 = 0;
        while i < count {
            self.entries[i as usize] = None;
            i = i + 1;
        }
        self.len = 0;
        count
    }
}

// === End stubs ===

// Verified timer model for Zephyr RTOS.
//
// This is a formally verified model of Zephyr's k_timer kernel object.
// All safety-critical properties are proven with Verus (SMT/Z3).
//
// This module models the **expiry counter and state** of Zephyr's timer.
// Actual timeout scheduling and callback dispatch remain in C — only
// the status counter, period, and running flag cross the FFI boundary.
//
// Source mapping:
//   k_timer_init        -> Timer::init        (timer.c init)
//   k_timer_start       -> Timer::start       (timer.c start)
//   k_timer_stop        -> Timer::stop        (timer.c stop)
//   k_timer_status_get  -> Timer::status_get  (timer.c status_get: read + reset)
//   k_timer_status_sync -> (not modeled)      (waits for expiry — scheduling)
//
// Omitted (not safety-relevant):
//   - CONFIG_OBJ_CORE_TIMER — debug/tracing
//   - CONFIG_USERSPACE (z_vrfy_*) — syscall marshaling
//   - SYS_PORT_TRACING_* — instrumentation
//   - k_timer_user_data_set/get — application data pointer
//   - k_timer_expires_ticks / k_timer_remaining_ticks — timing queries
//   - k_timer_status_sync — blocking wait (scheduling concern)
//   - expiry_fn / stop_fn callbacks — dispatched by C scheduler
//
// ASIL-D verified properties:
//   TM1: status >= 0 (trivially true for u32)
//   TM2: status_get returns old value and sets status = 0
//   TM3: start sets status = 0
//   TM4: stop sets status = 0, running = false
//   TM5: expiry increments status by 1 (checked_add)
//   TM6: period == 0 after init(_, 0) (one-shot)
//   TM7: period > 0 after init(_, p>0) (periodic)
//   TM8: no overflow (checked_add returns error on overflow)
/// Timer state model — expiry counter + period + running flag.
///
/// Corresponds to Zephyr's struct k_timer {
///     struct _timeout timeout;   // scheduling (not modeled)
///     struct k_work_delayable work; // (not modeled)
///     uint32_t status;           // expiry count since last read
///     uint32_t period;           // 0 = one-shot, >0 = periodic (ticks)
/// };
///
/// We model the running state explicitly; in Zephyr it is implicit
/// (timeout node linked into the timeout queue).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Timer {
    /// Expiry counter: incremented on each expiry, reset on get/start/stop.
    pub status: u32,
    /// Timer period in ticks: 0 = one-shot, >0 = periodic.
    pub period: u32,
    /// Whether the timer is actively running.
    pub running: bool,
}
impl Timer {
    /// Initialize a timer with given period.
    ///
    /// Period 0 means one-shot; period > 0 means periodic.
    /// Timer starts in the stopped state.
    pub fn init(period: u32) -> Timer {
        Timer {
            status: 0,
            period,
            running: false,
        }
    }
    /// Start the timer.
    ///
    /// Resets the status counter and marks the timer as running.
    /// TM3: start sets status = 0.
    pub fn start(&mut self) {
        self.status = 0;
        self.running = true;
    }
    /// Stop the timer.
    ///
    /// Resets the status counter and marks the timer as stopped.
    /// TM4: stop sets status = 0, running = false.
    pub fn stop(&mut self) {
        self.status = 0;
        self.running = false;
    }
    /// Record a timer expiry event.
    ///
    /// Increments the status counter by 1.
    /// Returns the new status value on success, or EOVERFLOW if the
    /// counter would overflow u32::MAX.
    ///
    /// TM5: expiry increments status by 1.
    /// TM8: no overflow (returns error on u32::MAX).
    pub fn expire(&mut self) -> Result<u32, i32> {
        if self.status == u32::MAX {
            Err(EOVERFLOW)
        } else {
            #[allow(clippy::arithmetic_side_effects)]
            {
                self.status = self.status + 1;
            }
            Ok(self.status)
        }
    }
    /// Read and reset the status counter.
    ///
    /// Returns the number of expiry events since the last status_get
    /// (or since start/stop), then resets the counter to 0.
    ///
    /// TM2: returns old value, sets status = 0.
    pub fn status_get(&mut self) -> u32 {
        let old_status = self.status;
        self.status = 0;
        old_status
    }
    /// Check if the timer is currently running.
    pub fn is_running(&self) -> bool {
        self.running
    }
    /// Get the timer period.
    pub fn period_get(&self) -> u32 {
        self.period
    }
    /// Peek at the status counter without resetting it.
    pub fn status_peek(&self) -> u32 {
        self.status
    }
}
/// Result of an expire decision.
#[derive(Debug)]
pub struct ExpireDecideResult {
    /// New status value (status + 1, or unchanged on saturation).
    pub new_status: u32,
    /// Whether the timer has a non-zero period (periodic vs one-shot).
    pub is_periodic: bool,
}
/// Lightweight expire decision — takes scalars, no Timer allocation.
///
/// Verified properties (TM5, TM8):
/// - status < u32::MAX ==> new_status == status + 1
/// - status == u32::MAX ==> new_status == u32::MAX (saturated)
/// - is_periodic == (period > 0)
pub fn expire_decide(status: u32, period: u32) -> ExpireDecideResult {
    let new_status = if status < u32::MAX { status + 1 } else { status };
    ExpireDecideResult {
        new_status,
        is_periodic: period > 0,
    }
}