//! Emit the per-target Rust constants module from a resolved `Target`.
//!
//! These constants replace the hand-scattered magic numbers in the silicon
//! firmware. `RCC_CSR` is derived as `rcc.Base + rcc.Csr_Offset`; `IWDGRSTF`
//! and `RMVF` are emitted as `1 << <bit>` from the RCC reset-flag bit indices,
//! so the F1/G4 difference (offset 0x24/0x94, RMVF bit 24/23) comes entirely
//! from the AADL model, not from edited code.

use crate::model::{Device, Target};

/// Source model file stem from the target's package part, e.g.
/// `"STM32F100::Board.vldiscovery"` -> `"stm32f100"`.
fn model_stem(target_name: &str) -> String {
    target_name
        .split("::")
        .next()
        .unwrap_or(target_name)
        .to_lowercase()
}

/// Format a 32-bit value as `0xHHHH_LLLL` (16-bit grouped hex).
fn hex(v: u32) -> String {
    format!("0x{:04X}_{:04X}", v >> 16, v & 0xFFFF)
}

fn device<'a>(t: &'a Target, name: &str) -> &'a Device {
    t.devices
        .iter()
        .find(|d| d.name == name)
        .unwrap_or_else(|| panic!("gust-target-gen: target `{}` has no `{name}` device", t.name))
}

fn rcc_prop(rcc: &Device, key: &str) -> u32 {
    *rcc.props
        .get(key)
        .unwrap_or_else(|| panic!("gust-target-gen: Rcc device missing `{key}` property"))
}

/// Emit the per-target constants module (IWDG/RCC/memory) as Rust source.
pub fn emit_rs(t: &Target) -> String {
    let iwdg = device(t, "Iwdg");
    let rcc = device(t, "Rcc");
    let csr_off = rcc_prop(rcc, "Csr_Offset");
    let iwdgrstf = rcc_prop(rcc, "Iwdgrstf_Bit");
    let rmvf = rcc_prop(rcc, "Rmvf_Bit");
    let stem = model_stem(&t.name);
    format!(
        "// GENERATED by gust-target-gen from {stem}.aadl — DO NOT EDIT\n\
         // Source of truth: benches/gust/targets/{stem}.aadl (spar/AADL model).\n\
         pub const IWDG_BASE: u32 = {iwdg_base};\n\
         pub const RCC_CSR: u32 = {rcc_csr};\n\
         pub const IWDGRSTF: u32 = 1 << {iwdgrstf};\n\
         pub const RMVF: u32 = 1 << {rmvf};\n\
         pub const FLASH_BASE: u32 = {flash_base};\n\
         pub const FLASH_LEN: u32 = {flash_len};\n\
         pub const SRAM_BASE: u32 = {sram_base};\n\
         pub const SRAM_LEN: u32 = {sram_len};\n",
        iwdg_base = hex(iwdg.base),
        rcc_csr = hex(rcc.base + csr_off),
        flash_base = hex(t.flash.base),
        flash_len = t.flash.len,
        sram_base = hex(t.sram.base),
        sram_len = t.sram.len,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::parse_items;

    // One `spar items --format json` fixture holds every target package, so
    // both boards are resolved from it (F1/G4 differ only in the model values).
    const ITEMS: &str = include_str!("../tests/golden/f100.items.json");

    #[test]
    fn emits_f100_consts_matching_golden() {
        let t = parse_items(ITEMS, "STM32F100::Board.vldiscovery");
        assert_eq!(
            emit_rs(&t),
            include_str!("../tests/golden/gust_target_stm32f100.rs.expected")
        );
    }

    #[test]
    fn emits_g474_consts_matching_golden() {
        let t = parse_items(ITEMS, "STM32G474::Board.nucleo");
        assert_eq!(
            emit_rs(&t),
            include_str!("../tests/golden/gust_target_stm32g474.rs.expected")
        );
    }

    /// Keystone parity: the generated constants equal the exact values
    /// gust_wdg_silicon.rs hardcoded BEFORE the retarget (git-recorded) — so the
    /// retarget cannot silently change what the firmware programs.
    ///   G4: IWDG_BASE=0x40003000, RCC_CSR=0x40021094, IWDGRSTF bit 29, RMVF bit 23
    ///   F1: IWDG_BASE=0x40003000, RCC_CSR=0x40021024, IWDGRSTF bit 29, RMVF bit 24
    #[test]
    fn generated_consts_equal_prior_handwritten_firmware_values() {
        let g = emit_rs(&parse_items(ITEMS, "STM32G474::Board.nucleo"));
        assert!(g.contains("IWDG_BASE: u32 = 0x4000_3000;"), "g474 IWDG_BASE");
        assert!(g.contains("RCC_CSR: u32 = 0x4002_1094;"), "g474 RCC_CSR");
        assert!(g.contains("IWDGRSTF: u32 = 1 << 29;"), "g474 IWDGRSTF");
        assert!(g.contains("RMVF: u32 = 1 << 23;"), "g474 RMVF");

        let f = emit_rs(&parse_items(ITEMS, "STM32F100::Board.vldiscovery"));
        assert!(f.contains("IWDG_BASE: u32 = 0x4000_3000;"), "f100 IWDG_BASE");
        assert!(f.contains("RCC_CSR: u32 = 0x4002_1024;"), "f100 RCC_CSR");
        assert!(f.contains("IWDGRSTF: u32 = 1 << 29;"), "f100 IWDGRSTF");
        assert!(f.contains("RMVF: u32 = 1 << 24;"), "f100 RMVF");
    }
}
