//! Emit the per-target Rust constants module from a resolved `Target`.
//!
//! These constants replace the hand-scattered magic numbers in the silicon
//! firmware. `RCC_CSR` is derived as `rcc.Base + rcc.Csr_Offset`; `IWDGRSTF`
//! and `RMVF` are emitted as `1 << <bit>` from the RCC reset-flag bit indices,
//! so the F1/G4 difference (offset 0x24/0x94, RMVF bit 24/23) comes entirely
//! from the AADL model, not from edited code.

use crate::model::{Device, Target};

/// Source model file stem from the target's package part, e.g.
/// `"STM32F100::Board.vldiscovery"` -> `"stm32f100"`.
fn model_stem(target_name: &str) -> String {
    target_name
        .split("::")
        .next()
        .unwrap_or(target_name)
        .to_lowercase()
}

/// Format a 32-bit value as `0xHHHH_LLLL` (16-bit grouped hex).
fn hex(v: u32) -> String {
    format!("0x{:04X}_{:04X}", v >> 16, v & 0xFFFF)
}

fn device<'a>(t: &'a Target, name: &str) -> &'a Device {
    t.devices
        .iter()
        .find(|d| d.name == name)
        .unwrap_or_else(|| panic!("gust-target-gen: target `{}` has no `{name}` device", t.name))
}

/// Like `device`, but returns `None` instead of panicking when the target's
/// model has no device of that name — for peripherals not every board has
/// (e.g. `Adc`), so their consts are emitted only when the model carries them.
fn device_opt<'a>(t: &'a Target, name: &str) -> Option<&'a Device> {
    t.devices.iter().find(|d| d.name == name)
}

fn rcc_prop(rcc: &Device, key: &str) -> u32 {
    *rcc.props
        .get(key)
        .unwrap_or_else(|| panic!("gust-target-gen: Rcc device missing `{key}` property"))
}

/// Optional peripheral devices and the constants each contributes:
/// `(AADL device type, const prefix, [(offset property, register const suffix)])`.
///
/// A peripheral enters this table DELIBERATELY, like `emit_wit::interfaces_for`.
/// A device in a board's model with no entry here emits nothing, and an entry
/// whose offset property that board's model omits emits nothing for that
/// register — so a board only ever gets constants its OWN model carries, and a
/// board without the peripheral (e.g. the G4 model, which has no proven bases)
/// keeps byte-identical output.
///
/// `<PREFIX>_BASE` is the device `Base`; each register const is `Base + offset`,
/// which is where the base-vs-offset distinction is enforced: `USART1_DR` is
/// derived, never modelled as a device of its own.
type Regs = &'static [(&'static str, &'static str)];

const USART_REGS: Regs = &[
    ("Sr_Offset", "SR"),
    ("Dr_Offset", "DR"),
    ("Brr_Offset", "BRR"),
    ("Cr1_Offset", "CR1"),
];
// One F1 GPIO port register map, shared by every port device — which offsets a
// given port actually emits is the board model's call, not this table's.
const GPIO_REGS: Regs = &[("Crh_Offset", "CRH"), ("Bsrr_Offset", "BSRR")];
const TIM_REGS: Regs = &[("Cnt_Offset", "CNT")];
const SPI_REGS: Regs = &[
    ("Cr1_Offset", "CR1"),
    ("Sr_Offset", "SR"),
    ("Dr_Offset", "DR"),
];

const PERIPHERALS: &[(&str, &str, Regs)] = &[
    ("Usart1", "USART1", USART_REGS),
    ("Gpioa", "GPIOA", GPIO_REGS),
    ("Gpioc", "GPIOC", GPIO_REGS),
    ("Tim2", "TIM2", TIM_REGS),
    ("Spi1", "SPI1", SPI_REGS),
];

/// Emit the per-target constants module (IWDG/RCC/memory) as Rust source.
pub fn emit_rs(t: &Target) -> String {
    let iwdg = device(t, "Iwdg");
    let rcc = device(t, "Rcc");
    let csr_off = rcc_prop(rcc, "Csr_Offset");
    let iwdgrstf = rcc_prop(rcc, "Iwdgrstf_Bit");
    let rmvf = rcc_prop(rcc, "Rmvf_Bit");
    let stem = model_stem(&t.name);
    let board = stem.to_uppercase();
    let mut out = format!(
        "// GENERATED by gust-target-gen from {stem}.aadl — DO NOT EDIT\n\
         // Source of truth: benches/gust/targets/{stem}.aadl (spar/AADL model).\n\
         pub const BOARD: &str = \"{board}\";\n\
         pub const IWDG_BASE: u32 = {iwdg_base};\n\
         pub const RCC_CSR: u32 = {rcc_csr};\n\
         pub const IWDGRSTF: u32 = 1 << {iwdgrstf};\n\
         pub const RMVF: u32 = 1 << {rmvf};\n\
         pub const FLASH_BASE: u32 = {flash_base};\n\
         pub const FLASH_LEN: u32 = {flash_len};\n\
         pub const SRAM_BASE: u32 = {sram_base};\n\
         pub const SRAM_LEN: u32 = {sram_len};\n",
        iwdg_base = hex(iwdg.base),
        rcc_csr = hex(rcc.base + csr_off),
        flash_base = hex(t.flash.base),
        flash_len = t.flash.len,
        sram_base = hex(t.sram.base),
        sram_len = t.sram.len,
    );

    // RCC_APB2ENR — the APB2 peripheral-clock-enable register. Only modelled
    // where it is proven (the F1 model, silicon-anchored by gust_adc_silicon);
    // a board whose model omits the offset emits nothing.
    if let Some(&apb2enr_off) = rcc.props.get("Apb2enr_Offset") {
        out.push_str(&format!(
            "pub const RCC_APB2ENR: u32 = {};\n",
            hex(rcc.base + apb2enr_off)
        ));
    }

    // ADC is not present on every board (e.g. G4 has no Adc device in its
    // model) — emit its consts only when the model actually carries them,
    // so boards without an ADC get byte-identical output to before.
    if let Some(adc) = device_opt(t, "Adc") {
        if let Some(&vrefint_ch) = adc.props.get("Vrefint_Ch") {
            out.push_str(&format!(
                "pub const ADC_BASE: u32 = {adc_base};\n\
                 pub const VREFINT_CH: u32 = {vrefint_ch};\n",
                adc_base = hex(adc.base),
            ));
        }
    }

    // MPU presence is a HARDWARE FACT, not a build option, and it decides whether a
    // target can host REQ-OS-MPU-001 / REQ-OS-UNPRIV-001 / REQ-OS-MULTITENANT-001 at
    // all. It is emitted for every board that declares an Mpu device, INCLUDING one
    // that declares it absent: "this part has no MPU" is an answer, and a missing
    // const is not. Measured, not assumed -- the STM32F100 reads MPU_TYPE == 0.
    // REQUIRED, not optional. A target that simply omits the device would emit no
    // const at all, and a consumer asking "can this target isolate?" would get a
    // compile error it could paper over rather than an answer. Same stance as
    // interfaces_for()'s unknown-class panic: a new board must SAY, and "no MPU" is
    // a perfectly good thing to say (the STM32F100 says it).
    let mpu = device_opt(t, "Mpu").unwrap_or_else(|| {
        panic!(
            "gust-target-gen: target `{}` declares no Mpu device. MPU presence decides \
             whether it can host REQ-OS-MPU-001 / REQ-OS-UNPRIV-001 / \
             REQ-OS-MULTITENANT-001 at all, so it must be declared explicitly — \
             `Present => false; Dregion => 0;` if the part has none.",
            t.name
        )
    });
    {
        let dregion = mpu.props.get("Dregion").copied().unwrap_or(0);
        out.push_str(&format!(
            "pub const MPU_PRESENT: bool = {present};\n\
             pub const MPU_DREGION: u32 = {dregion};\n",
            present = mpu.present,
        ));
    }

    // Peripherals whose bases the board's model carries (see PERIPHERALS).
    for (dev, prefix, regs) in PERIPHERALS {
        if let Some(d) = device_opt(t, dev) {
            out.push_str(&format!(
                "pub const {prefix}_BASE: u32 = {base};\n",
                base = hex(d.base)
            ));
            for (key, suffix) in *regs {
                if let Some(&off) = d.props.get(*key) {
                    out.push_str(&format!(
                        "pub const {prefix}_{suffix}: u32 = {addr};\n",
                        addr = hex(d.base + off)
                    ));
                }
            }
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::parse_items;

    // One `spar items --format json` fixture holds every target package, so
    // both boards are resolved from it (F1/G4 differ only in the model values).
    const ITEMS: &str = include_str!("../tests/golden/f100.items.json");

    #[test]
    fn emits_f100_consts_matching_golden() {
        let t = parse_items(ITEMS, "STM32F100::Board.vldiscovery");
        assert_eq!(
            emit_rs(&t),
            include_str!("../tests/golden/gust_target_stm32f100.rs.expected")
        );
    }

    #[test]
    fn emits_g474_consts_matching_golden() {
        let t = parse_items(ITEMS, "STM32G474::Board.nucleo");
        assert_eq!(
            emit_rs(&t),
            include_str!("../tests/golden/gust_target_stm32g474.rs.expected")
        );
    }

    /// Keystone parity: the generated constants equal the exact values
    /// gust_wdg_silicon.rs hardcoded BEFORE the retarget (git-recorded) — so the
    /// retarget cannot silently change what the firmware programs.
    ///   G4: IWDG_BASE=0x40003000, RCC_CSR=0x40021094, IWDGRSTF bit 29, RMVF bit 23
    ///   F1: IWDG_BASE=0x40003000, RCC_CSR=0x40021024, IWDGRSTF bit 29, RMVF bit 24
    #[test]
    fn generated_consts_equal_prior_handwritten_firmware_values() {
        let g = emit_rs(&parse_items(ITEMS, "STM32G474::Board.nucleo"));
        assert!(g.contains("IWDG_BASE: u32 = 0x4000_3000;"), "g474 IWDG_BASE");
        assert!(g.contains("RCC_CSR: u32 = 0x4002_1094;"), "g474 RCC_CSR");
        assert!(g.contains("IWDGRSTF: u32 = 1 << 29;"), "g474 IWDGRSTF");
        assert!(g.contains("RMVF: u32 = 1 << 23;"), "g474 RMVF");

        let f = emit_rs(&parse_items(ITEMS, "STM32F100::Board.vldiscovery"));
        assert!(f.contains("IWDG_BASE: u32 = 0x4000_3000;"), "f100 IWDG_BASE");
        assert!(f.contains("RCC_CSR: u32 = 0x4002_1024;"), "f100 RCC_CSR");
        assert!(f.contains("IWDGRSTF: u32 = 1 << 29;"), "f100 IWDGRSTF");
        assert!(f.contains("RMVF: u32 = 1 << 24;"), "f100 RMVF");
    }

    /// Keystone parity for the F100 peripheral devices: every emitted constant
    /// equals the value the in-tree firmware/driver ALREADY hardcodes, so
    /// modelling a peripheral cannot silently move it. Each right-hand side is
    /// lifted from a specific in-tree use:
    ///   RCC_APB2ENR 0x40021018  gust_adc_silicon.rs (real F100 silicon)
    ///   USART1_*    0x40013800  drivers/uart-thin/src/lib.rs (+SR/DR/BRR/CR1)
    ///   GPIOA_CRH   0x40010804  gust_uart.rs PA9 alternate-function setup
    ///   GPIOC_*     0x40011000  gust_gpio.rs / drivers/gpio-thin (CRH, BSRR)
    ///   TIM2_CNT    0x40000024  drivers/time-provider/src/lib.rs
    ///   SPI1_*      0x40013000  gust_spi.rs / drivers/spi-thin (CR1, SR, DR)
    #[test]
    fn f100_peripheral_consts_equal_the_intree_hardcoded_addresses() {
        let f = emit_rs(&parse_items(ITEMS, "STM32F100::Board.vldiscovery"));
        for expected in [
            "pub const RCC_APB2ENR: u32 = 0x4002_1018;",
            "pub const USART1_BASE: u32 = 0x4001_3800;",
            "pub const USART1_SR: u32 = 0x4001_3800;",
            "pub const USART1_DR: u32 = 0x4001_3804;",
            "pub const USART1_BRR: u32 = 0x4001_3808;",
            "pub const USART1_CR1: u32 = 0x4001_380C;",
            "pub const GPIOA_BASE: u32 = 0x4001_0800;",
            "pub const GPIOA_CRH: u32 = 0x4001_0804;",
            "pub const GPIOC_BASE: u32 = 0x4001_1000;",
            "pub const GPIOC_CRH: u32 = 0x4001_1004;",
            "pub const GPIOC_BSRR: u32 = 0x4001_1010;",
            "pub const TIM2_BASE: u32 = 0x4000_0000;",
            "pub const TIM2_CNT: u32 = 0x4000_0024;",
            "pub const SPI1_BASE: u32 = 0x4001_3000;",
            "pub const SPI1_CR1: u32 = 0x4001_3000;",
            "pub const SPI1_SR: u32 = 0x4001_3008;",
            "pub const SPI1_DR: u32 = 0x4001_300C;",
        ] {
            assert!(f.contains(expected), "f100 missing `{expected}`");
        }
    }

    /// The G4 memory map is NOT the F1 memory map: no F100 peripheral base may
    /// leak into the G474 output. Only Iwdg/Rcc are proven on that part, so the
    /// G4 module must carry no peripheral constants at all.
    #[test]
    fn g474_gets_no_unproven_peripheral_consts() {
        let g = emit_rs(&parse_items(ITEMS, "STM32G474::Board.nucleo"));
        for absent in [
            "RCC_APB2ENR",
            "USART1_",
            "GPIOA_",
            "GPIOC_",
            "TIM2_",
            "SPI1_",
            "ADC_BASE",
        ] {
            assert!(!g.contains(absent), "g474 must not emit `{absent}`");
        }
    }
}
