//! Emit the per-target gust:hal WIT world from a resolved `Target`.
//!
//! The world imports exactly the gust:hal interfaces the target's *present*
//! devices require — the swap/extend mechanism. A board that gains a peripheral
//! (e.g. bxCAN on an F103-class part) imports that peripheral's interface; a
//! board without it does not. IWDG/RCC need only the thin `mmio` seam.

use crate::model::Target;

fn model_stem(target_name: &str) -> String {
    target_name
        .split("::")
        .next()
        .unwrap_or(target_name)
        .to_lowercase()
}

/// The gust:hal interfaces a device CLASS requires. Adding a new peripheral
/// forces a deliberate entry here (unknown class -> panic), so presence can
/// never silently import nothing.
fn interfaces_for(device_class: &str) -> &'static [&'static str] {
    match device_class {
        "adc" => &["mmio"],
        "iwdg" => &["mmio"],
        "rcc" => &["mmio"],
        other => panic!(
            "gust-target-gen: no gust:hal interface mapping for device class `{other}` \
             — add it to interfaces_for()"
        ),
    }
}

/// Emit the per-target gust:hal WIT world contents.
pub fn emit_wit(t: &Target) -> String {
    let stem = model_stem(&t.name);

    let mut present: Vec<String> = t
        .devices
        .iter()
        .filter(|d| d.present)
        .map(|d| d.name.to_lowercase())
        .collect();

    // Union of required interfaces across present devices, sorted + deduped.
    let mut ifaces: Vec<&'static str> = present
        .iter()
        .flat_map(|name| interfaces_for(name).iter().copied())
        .collect();
    ifaces.sort_unstable();
    ifaces.dedup();

    present.sort();

    let imports: String = ifaces
        .iter()
        .map(|i| format!("    import gust:hal/{i}@0.1.0;\n"))
        .collect();

    format!(
        "// GENERATED by gust-target-gen from {stem}.aadl — DO NOT EDIT\n\
         package gust:target-{stem}@0.1.0;\n\
         world {stem} {{\n\
         {imports}    // devices present: {present_list}\n\
         }}\n",
        present_list = present.join(", "),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::parse_items;

    const ITEMS: &str = include_str!("../tests/golden/f100.items.json");

    #[test]
    fn emits_f100_world_matching_golden() {
        let t = parse_items(ITEMS, "STM32F100::Board.vldiscovery");
        assert_eq!(
            emit_wit(&t),
            include_str!("../tests/golden/world-stm32f100.wit.expected")
        );
    }

    #[test]
    fn emits_g474_world_matching_golden() {
        let t = parse_items(ITEMS, "STM32G474::Board.nucleo");
        assert_eq!(
            emit_wit(&t),
            include_str!("../tests/golden/world-stm32g474.wit.expected")
        );
    }
}
