//! Emit the linker `memory.x` MEMORY block from a resolved `Target`.
//!
//! FLASH comes from `t.flash`, RAM from `t.sram`. LENGTH is rendered as `K`/`M`
//! when the byte count divides evenly, else as a raw byte count — matching the
//! hand-written `benches/gust/silicon/memory-*.x` this supersedes.

use crate::model::{Region, Target};

fn model_stem(target_name: &str) -> String {
    target_name
        .split("::")
        .next()
        .unwrap_or(target_name)
        .to_lowercase()
}

/// `131072` -> `"128K"`, `1048576` -> `"1M"`, `98304` -> `"96K"`, else bytes.
fn length(bytes: u32) -> String {
    if bytes != 0 && bytes % (1024 * 1024) == 0 {
        format!("{}M", bytes / (1024 * 1024))
    } else if bytes != 0 && bytes % 1024 == 0 {
        format!("{}K", bytes / 1024)
    } else {
        bytes.to_string()
    }
}

fn region_line(name: &str, r: &Region) -> String {
    // name padded to 6 so the ':' aligns (FLASH: / RAM  :), matching memory-*.x.
    format!(
        "  {:<6}: ORIGIN = 0x{:08x}, LENGTH = {}",
        name,
        r.base,
        length(r.len)
    )
}

/// Emit the linker `memory.x` contents.
pub fn emit_ld(t: &Target) -> String {
    let stem = model_stem(&t.name);
    format!(
        "/* GENERATED by gust-target-gen from {stem}.aadl — DO NOT EDIT */\n\
         MEMORY\n\
         {{\n\
         {flash}\n\
         {ram}\n\
         }}\n",
        flash = region_line("FLASH", &t.flash),
        ram = region_line("RAM", &t.sram),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::parse_items;

    const ITEMS: &str = include_str!("../tests/golden/f100.items.json");

    #[test]
    fn emits_f100_memory_x_matching_golden() {
        let t = parse_items(ITEMS, "STM32F100::Board.vldiscovery");
        assert_eq!(
            emit_ld(&t),
            include_str!("../tests/golden/memory-f100.x.expected")
        );
    }

    #[test]
    fn emits_g474_memory_x_matching_golden() {
        let t = parse_items(ITEMS, "STM32G474::Board.nucleo");
        assert_eq!(
            emit_ld(&t),
            include_str!("../tests/golden/memory-g474re.x.expected")
        );
    }

    #[test]
    fn length_renders_k_m_and_bytes() {
        assert_eq!(length(131072), "128K");
        assert_eq!(length(8192), "8K");
        assert_eq!(length(524288), "512K");
        assert_eq!(length(98304), "96K");
        assert_eq!(length(1024 * 1024), "1M");
        assert_eq!(length(1000), "1000"); // not a K multiple -> raw bytes
    }
}
