CONFIG_GALE_KERNEL_SEM=y
CONFIG_GALE_KERNEL_MUTEX=y
CONFIG_GALE_KERNEL_CONDVAR=y
CONFIG_GALE_KERNEL_MSGQ=y
CONFIG_GALE_KERNEL_STACK=y
CONFIG_GALE_KERNEL_PIPE=y
CONFIG_GALE_KERNEL_EVENT=y
CONFIG_GALE_KERNEL_TIMER=y
CONFIG_GALE_KERNEL_MEM_SLAB=y
CONFIG_GALE_KERNEL_FIFO=y
CONFIG_GALE_KERNEL_LIFO=y
CONFIG_GALE_KERNEL_QUEUE=y
CONFIG_GALE_KERNEL_MBOX=y
