#!/usr/bin/env python3
"""Upstream-vs-gale kernel test delta — what gale's replacements actually change.

gale#395. The "Zephyr C Coverage" job measures upstream Zephyr with every gale
replacement switched off (0 gale symbols in its build). So it is no evidence about
gale. This compares two twister runs over the SAME test selection on the SAME
platform, differing ONLY in whether gale's module + overlay are injected:

  upstream  : --platform qemu_cortex_m3 --tag kernel
  gale      : same, plus ZEPHYR_EXTRA_MODULES=gale + gale_overlay.conf

The per-suite OUTCOME diff is the headline, and the most important row is:

  passes upstream, fails with gale  ->  a regression gale introduces

That is the one thing no other gate here can show, because every other Zephyr test
job either excludes gale (this one did) or has no upstream baseline to compare to.

Coverage (lcov) is reported when both runs produced it, and reported as ABSENT
when they did not — never silently skipped. A measurement that quietly omits its
own headline number is the defect class gale#389 was filed against.

Usage:  coverage-delta.py UPSTREAM_TWISTER_JSON GALE_TWISTER_JSON [--summary FILE]
Exit:   0 = measured (a regression is reported, not a crash)
        2 = could not measure (missing/unreadable/empty input)
        3 = gale introduced a regression AND --fail-on-regression was given
"""
import json
import pathlib
import sys

EXECUTED_OUT = {None, "filtered", "skipped", "not run"}


def load(path):
    p = pathlib.Path(path)
    if not p.is_file() or p.stat().st_size == 0:
        return None, f"{path}: missing or empty"
    try:
        d = json.loads(p.read_text())
    except ValueError as e:
        return None, f"{path}: not JSON ({e})"
    suites = d.get("testsuites")
    if not isinstance(suites, list):
        return None, f"{path}: no testsuites list"
    return {s.get("name"): s.get("status") for s in suites if s.get("name")}, None


def executed(outcomes):
    return {n: s for n, s in outcomes.items() if s not in EXECUTED_OUT}


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    fail_on_regression = "--fail-on-regression" in argv
    summary = None
    if "--summary" in argv:
        i = argv.index("--summary")
        summary = argv[i + 1] if i + 1 < len(argv) else None
        args = [a for a in args if a != summary]
    if len(args) != 2:
        print(__doc__)
        return 2

    up, e1 = load(args[0])
    ga, e2 = load(args[1])
    if e1 or e2:
        for e in (e1, e2):
            if e:
                print(f"::error::cannot measure — {e}")
        return 2

    upx, gax = executed(up), executed(ga)
    # Vacuity guard: a comparison of two runs that executed nothing is not a result.
    if not upx or not gax:
        print(f"::error::cannot measure — executed suites: upstream={len(upx)} gale={len(gax)}")
        return 2

    both = sorted(set(upx) & set(gax))
    regressions = [n for n in both if upx[n] == "passed" and gax[n] in ("failed", "error")]
    fixes       = [n for n in both if upx[n] in ("failed", "error") and gax[n] == "passed"]
    still_fail  = [n for n in both if upx[n] in ("failed", "error") and gax[n] in ("failed", "error")]
    only_up     = sorted(set(upx) - set(gax))
    only_gale   = sorted(set(gax) - set(upx))

    def count(o, st):
        return sum(1 for v in o.values() if v == st)

    lines = [
        "## Upstream vs gale — kernel tests on qemu_cortex_m3",
        "",
        "| | upstream | gale |",
        "|---|---|---|",
        f"| executed | {len(upx)} | {len(gax)} |",
        f"| passed | {count(upx,'passed')} | {count(gax,'passed')} |",
        f"| failed | {count(upx,'failed')} | {count(gax,'failed')} |",
        f"| error | {count(upx,'error')} | {count(gax,'error')} |",
        "",
        f"**Compared on {len(both)} suites executed by both.**",
        "",
        f"### Regressions gale introduces — pass upstream, fail with gale: **{len(regressions)}**",
    ]
    lines += [f"- `{n}`" for n in regressions] or ["- none"]
    lines += ["", f"### Fixed by gale — fail upstream, pass with gale: {len(fixes)}"]
    lines += [f"- `{n}`" for n in fixes] or ["- none"]
    lines += ["", f"### Fail in both (not gale's doing): {len(still_fail)}"]
    lines += [f"- `{n}`" for n in still_fail] or ["- none"]
    if only_up or only_gale:
        lines += ["", "### Executed by only one side — NOT compared, listed so they are not mistaken for passes",
                  f"- upstream only: {len(only_up)}", f"- gale only: {len(only_gale)}"]
        lines += [f"  - `{n}` (upstream only)" for n in only_up[:15]]
        lines += [f"  - `{n}` (gale only)" for n in only_gale[:15]]
    lines += ["", "### Coverage",
              "Not generated by either run yet (twister emits no coverage report here — gale#394). "
              "Reported as absent rather than omitted."]

    text = "\n".join(lines)
    print(text)
    if summary:
        with open(summary, "a") as fh:
            fh.write(text + "\n")

    if regressions and fail_on_regression:
        print(f"::error::gale introduces {len(regressions)} regression(s)")
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
